// <auto-generated />
namespace ImageUploadViewDemo.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class Employeetableorderoftablechangednewupdate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Employeetableorderoftablechangednewupdate));
        
        string IMigrationMetadata.Id
        {
            get { return "201912221527113_Employee table order of table changed new update"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
